<a href="https://colab.research.google.com/github/Mubassir1820/PyTorch-fundamentals/blob/main/__PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [96]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

## Creating tensors

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [97]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [98]:
# details(dimension) about scalar tensor

scalar.ndim

0

In [99]:
#get tensor back as python int

scalar.item()

7

In [100]:
#vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [101]:
vector.ndim

1

In [102]:
vector.shape

torch.Size([2])

In [103]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [104]:
MATRIX.ndim

2

In [105]:
MATRIX[0]

tensor([7, 8])

In [106]:
MATRIX.shape

torch.Size([2, 2])

In [107]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [108]:
TENSOR.ndim

3

In [109]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

why random tensors??

Random tensors are important because the way many neutral networks learn is that they start with full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> Look at data -> update random numbers

start with random numbers - https://pytorch.org/docs/stable/generated/torch.rand.html

In [110]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [111]:
random_tensor.ndim

2

In [112]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3))# height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [113]:
torch.rand(3,3)

tensor([[0.5745, 0.9200, 0.3230],
        [0.8613, 0.0919, 0.3102],
        [0.9536, 0.6002, 0.0351]])

### Zeros and Ones

In [114]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [115]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [116]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [117]:
ones.dtype

torch.float32

In [118]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [119]:
# Use torch.range()
one_to_ten  = torch.arange(start = 0, end = 1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [120]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with pyTorch and Deep learning:
1. Tensors not right datatype
2. Tensors no right shape
3. Tensors not on the right device

In [121]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor
                               device = None, # what device is your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [122]:
float_32_tensor.dtype

torch.float32

In [123]:
# how to change datatypes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [124]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [125]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [126]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors(tensor attributes)

1. Tensors not right datatype - To get datatype from a tensor, can use tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [127]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6826, 0.3743, 0.5220, 0.1336],
        [0.9666, 0.9754, 0.8474, 0.8988],
        [0.1105, 0.4563, 0.9719, 0.3968]])

In [128]:
# find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.6826, 0.3743, 0.5220, 0.1336],
        [0.9666, 0.9754, 0.8474, 0.8988],
        [0.1105, 0.4563, 0.9719, 0.3968]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

Tensor operation include:
*Addition
*Subtraction
*Multiplication
*Division
*Matrix multiplication

In [129]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [130]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [131]:
# Subtract 10

tensor - 10

tensor([-9, -8, -7])

In [132]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:
1.Element wise multiplication
2.Matrix multiplication(dot product)


In [133]:
# Element wise multiplication
print(tensor,'*' , tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [134]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [135]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

### One of the most common error in deep learning is shape error

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
2. The resulting matrix has the shape of outer dimension
* (2,3) @ (3,2) -> (2,2)

In [136]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.4082, 0.6593],
        [0.6517, 1.1737]])

In [137]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul

RuntimeError: ignored

In [138]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate one of our tensor shape using **transpose**

A transpose switches the axis or dimensions of a given tensor

In [139]:
tensor_B.T #transpose 

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [140]:
tensor_B.T.shape

torch.Size([2, 3])

In [141]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: {tensor_A.shape}, {tensor_B.shape}')
print(f'New shapes: {tensor_A.shape}, {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output: \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')


Original shapes: torch.Size([3, 2]), torch.Size([3, 2])
New shapes: torch.Size([3, 2]), torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc(tensor aggregation)

In [142]:
# create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [143]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [144]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [145]:
# find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [146]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positonal min and max

In [147]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [148]:
# Find the position in tensor that has the min value with argmin() -> returns the index position
x.argmin()

tensor(0)

In [149]:
x[0]

tensor(0)

In [150]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [151]:
x[9]

tensor(90)

### Reshaping, Stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original one
* Stacking - combine multiple tensors of top of each others(vstack) or side by side (hstack)
* Squeeze - removes all 1 dimension from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [152]:
# Lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [154]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
# changing z changes x(because a view tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [156]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [157]:
# torch.squeeze - removes all single dimension from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'\nNew shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [158]:
x_reshaped.shape

torch.Size([1, 9])

In [159]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [160]:
x_reshaped.squeeze().shape

torch.Size([9])

In [161]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f'previous target: {x_squeezed}')
print(f'previous shape: {x_squeezed.shape}')

# add an extra dimension with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'\nNew shape: {x_unsqueezed.shape}')

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [162]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
x_original =  torch.rand(size = (224,224,3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # rearranged to [color_channel, height, width]

print(f'previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

indexing with PyTorch is similar to indexing with numPy

In [163]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [164]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [165]:
# Lets index on middle bracket
x[0, 0]

tensor([1, 2, 3])

In [166]:
# Lets index on the most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [167]:
# you can also use ':' to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [168]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [169]:
# Get all the values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [170]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimesion
x[0, 0, :]

tensor([1, 2, 3])

In [171]:
# index on x to return 9
x[0, 2, 2]

# index on x to return 3,6,9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors and Numpy

NumPy is a popular scientific python numerical computing library and becaause of this pytorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarraay)
*PyTorch tensor -> NumPy -> torch.tensor.numpy()

In [172]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch , pytorch reflects numpys default datatype of flot64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [173]:
array.dtype

dtype('float64')

In [174]:
torch.arange(1.0,8.0).dtype

torch.float32

In [175]:
# change the value of array, whaat will this do to tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [176]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [177]:
# change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility(trying to take random out of random) 

In short how a neural network learns:

'Start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the daata -> again -> again -> again

to reduce the randomness in neural network and pytorch comes the concept of a **radom seed**

Essentially what the random seed does is flavour the randomness

In [178]:
torch.rand(3,3)

tensor([[0.3708, 0.0831, 0.0944],
        [0.6568, 0.7708, 0.1053],
        [0.1467, 0.1932, 0.9118]])

In [179]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1488, 0.0913, 0.4470, 0.2440],
        [0.5571, 0.1928, 0.0602, 0.5837],
        [0.0009, 0.7581, 0.5817, 0.4338]])
tensor([[0.0333, 0.3746, 0.7110, 0.5946],
        [0.9475, 0.6228, 0.0768, 0.7122],
        [0.3727, 0.8434, 0.7186, 0.8834]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [180]:
# Lets make some random but reproducable tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # applicable only for a single block of code

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # to apply for random_tensor_D

random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyToch objects on the GPUs(and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch wroking behind the scenes to make everything hunky

###1. Getting a gpu

1. Easiest = Use google colab for a free gpu(options to upgraae a well)
2. Use your own GPU = 
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rend coputers on the cloud and access them

In [1]:
!nvidia-smi

Thu May 25 06:12:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available() # change the runtime type to gpu

True

In [3]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
# count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on the GPU

The reason we want our tensors/models on the gpu is beacuase using a GPU results in faster computation

In [5]:
# Crete a tensor(the default is on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print([tensor, tensor.device]) 

[tensor([1, 2, 3]), device(type='cpu')]


In [6]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, cant transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [9]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')