<a href="https://colab.research.google.com/github/Mubassir1820/PyTorch-fundamentals/blob/main/__PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

## Creating tensors

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# details(dimension) about scalar tensor

scalar.ndim

0

In [5]:
#get tensor back as python int

scalar.item()

7

In [6]:
#vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

why random tensors??

Random tensors are important because the way many neutral networks learn is that they start with full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> Look at data -> update random numbers

start with random numbers - https://pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8611, 0.9624, 0.7715, 0.3761],
        [0.5324, 0.7815, 0.9039, 0.0900],
        [0.7846, 0.7681, 0.2731, 0.7178]])

In [23]:
random_tensor.ndim

2

In [24]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3))# height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)