<a href="https://colab.research.google.com/github/Mubassir1820/PyTorch-fundamentals/blob/main/__PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

## Creating tensors

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# details(dimension) about scalar tensor

scalar.ndim

0

In [6]:
#get tensor back as python int

scalar.item()

7

In [7]:
#vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])