<a href="https://colab.research.google.com/github/Mubassir1820/PyTorch-fundamentals/blob/main/__PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

## Creating tensors

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# details(dimension) about scalar tensor

scalar.ndim

0

In [5]:
#get tensor back as python int

scalar.item()

7

In [6]:
#vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

why random tensors??

Random tensors are important because the way many neutral networks learn is that they start with full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> Look at data -> update random numbers

start with random numbers - https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3839, 0.4019, 0.0116, 0.9422],
        [0.3647, 0.1024, 0.6854, 0.3180],
        [0.4915, 0.7828, 0.6534, 0.6696]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3))# height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
torch.rand(3,3)

tensor([[0.5868, 0.1016, 0.2673],
        [0.3311, 0.7069, 0.9053],
        [0.8550, 0.0190, 0.7461]])

### Zeros and Ones

In [20]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
one_to_ten  = torch.arange(start = 0, end = 1000, step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with pyTorch and Deep learning:
1. Tensors not right datatype
2. Tensors no right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor
                               device = None, # what device is your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# how to change datatypes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors(tensor attributes)

1. Tensors not right datatype - To get datatype from a tensor, can use tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [33]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6497, 0.2666, 0.4997, 0.0210],
        [0.0104, 0.3688, 0.3906, 0.6087],
        [0.6005, 0.2532, 0.8703, 0.4507]])

In [34]:
# find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.6497, 0.2666, 0.4997, 0.0210],
        [0.0104, 0.3688, 0.3906, 0.6087],
        [0.6005, 0.2532, 0.8703, 0.4507]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

Tensor operation include:
*Addition
*Subtraction
*Multiplication
*Division
*Matrix multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
# Subtract 10

tensor - 10

tensor([-9, -8, -7])

In [38]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:
1.Element wise multiplication
2.Matrix multiplication(dot product)


In [39]:
# Element wise multiplication
print(tensor,'*' , tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

### One of the most common error in deep learning is shape error

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
2. The resulting matrix has the shape of outer dimension
* (2,3) @ (3,2) -> (2,2)

In [42]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.5260, 0.9086],
        [0.3347, 0.8521]])

In [43]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is same as torch.matmul

RuntimeError: ignored

In [44]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate one of our tensor shape using **transpose**

A transpose switches the axis or dimensions of a given tensor

In [45]:
tensor_B.T #transpose 

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
tensor_B.T.shape

torch.Size([2, 3])

In [47]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: {tensor_A.shape}, {tensor_B.shape}')
print(f'New shapes: {tensor_A.shape}, {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output: \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')


Original shapes: torch.Size([3, 2]), torch.Size([3, 2])
New shapes: torch.Size([3, 2]), torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc(tensor aggregation)

In [48]:
# create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [49]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [50]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [51]:
# find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positonal min and max

In [53]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
# Find the position in tensor that has the min value with argmin() -> returns the index position
x.argmin()

tensor(0)

In [55]:
x[0]

tensor(0)

In [56]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [57]:
x[9]

tensor(90)

### Reshaping, Stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original one
* Stacking - combine multiple tensors of top of each others(vstack) or side by side (hstack)
* Squeeze - removes all 1 dimension from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [58]:
# Lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# changing z changes x(because a view tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [64]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [69]:
# torch.squeeze - removes all single dimension from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'\nNew shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [66]:
x_reshaped.shape

torch.Size([1, 9])

In [67]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
x_reshaped.squeeze().shape

torch.Size([9])

In [71]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f'previous target: {x_squeezed}')
print(f'previous shape: {x_squeezed.shape}')

# add an extra dimension with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'\nNew shape: {x_unsqueezed.shape}')

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [72]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
x_original =  torch.rand(size = (224,224,3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # rearranged to [color_channel, height, width]

print(f'previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
